[package]
name = "difr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
hex = "0.4.3"
sha3 = "0.9.1"
clap = "3.0.0-beta.4"
